
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Editar_Empresa
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action INICIOAction;

		private global::Gtk.Action MENAction;

		private global::Gtk.VBox vbox20;

		private global::Gtk.MenuBar menubar13;

		private global::Gtk.Frame frame13;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox45;

		private global::Gtk.Button btnEditar;

		private global::Gtk.Button btnListar;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Label GtkLabel5;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvEmpresa;

		private global::Gtk.VBox vbox6;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label10;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label11;

		private global::Gtk.Entry txtTelefono;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label12;

		private global::Gtk.Entry txtDireccion;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label13;

		private global::Gtk.Entry txtRUC;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Editar_Empresa
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.INICIOAction = new global::Gtk.Action("INICIOAction", global::Mono.Unix.Catalog.GetString("INICIO"), null, null);
			this.INICIOAction.ShortLabel = global::Mono.Unix.Catalog.GetString("INICIO");
			w1.Add(this.INICIOAction, null);
			this.MENAction = new global::Gtk.Action("MENAction", global::Mono.Unix.Catalog.GetString("MENÚ"), null, null);
			this.MENAction.ShortLabel = global::Mono.Unix.Catalog.GetString("MENÚ");
			w1.Add(this.MENAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Editar_Empresa";
			this.Title = global::Mono.Unix.Catalog.GetString("Editar_Empresa");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Editar_Empresa.Gtk.Container+ContainerChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar13\'><menu name=\'INICIOAction\' action=\'INICIOAction\'/><m" +
					"enu name=\'MENAction\' action=\'MENAction\'/></menubar></ui>");
			this.menubar13 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar13")));
			this.menubar13.Name = "menubar13";
			this.vbox20.Add(this.menubar13);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.menubar13]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.frame13 = new global::Gtk.Frame();
			this.frame13.Name = "frame13";
			this.frame13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame13.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox45 = new global::Gtk.HBox();
			this.hbox45.Name = "hbox45";
			this.hbox45.Spacing = 6;
			// Container child hbox45.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.BorderWidth = ((uint)(15));
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar ");
			this.hbox45.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.btnEditar]));
			w3.Position = 0;
			// Container child hbox45.Gtk.Box+BoxChild
			this.btnListar = new global::Gtk.Button();
			this.btnListar.CanFocus = true;
			this.btnListar.Name = "btnListar";
			this.btnListar.UseUnderline = true;
			this.btnListar.BorderWidth = ((uint)(15));
			this.btnListar.Label = global::Mono.Unix.Catalog.GetString("Listar");
			this.hbox45.Add(this.btnListar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.btnListar]));
			w4.Position = 1;
			// Container child hbox45.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.BorderWidth = ((uint)(12));
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox45.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.btnAgregar]));
			w5.Position = 2;
			this.GtkAlignment.Add(this.hbox45);
			this.frame13.Add(this.GtkAlignment);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("EMPRESAS");
			this.GtkLabel5.UseMarkup = true;
			this.frame13.LabelWidget = this.GtkLabel5;
			this.vbox20.Add(this.frame13);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.frame13]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvEmpresa = new global::Gtk.TreeView();
			this.trvEmpresa.CanFocus = true;
			this.trvEmpresa.Name = "trvEmpresa";
			this.GtkScrolledWindow.Add(this.trvEmpresa);
			this.hbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w10.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.hbox3.Add(this.label10);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label10]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.hbox3.Add(this.txtNombre);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtNombre]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox7.Add(this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono:");
			this.hbox4.Add(this.label11);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label11]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txtTelefono = new global::Gtk.Entry();
			this.txtTelefono.CanFocus = true;
			this.txtTelefono.Name = "txtTelefono";
			this.txtTelefono.IsEditable = true;
			this.txtTelefono.InvisibleChar = '•';
			this.hbox4.Add(this.txtTelefono);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txtTelefono]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox7.Add(this.hbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox4]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion:");
			this.hbox5.Add(this.label12);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label12]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.txtDireccion = new global::Gtk.Entry();
			this.txtDireccion.CanFocus = true;
			this.txtDireccion.Name = "txtDireccion";
			this.txtDireccion.IsEditable = true;
			this.txtDireccion.InvisibleChar = '•';
			this.hbox5.Add(this.txtDireccion);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.txtDireccion]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox6.Add(this.vbox7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox7]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Numero RUC:");
			this.hbox6.Add(this.label13);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label13]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.txtRUC = new global::Gtk.Entry();
			this.txtRUC.CanFocus = true;
			this.txtRUC.Name = "txtRUC";
			this.txtRUC.IsEditable = false;
			this.txtRUC.InvisibleChar = '•';
			this.hbox6.Add(this.txtRUC);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.txtRUC]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox8.Add(this.hbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox6]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox6.Add(this.vbox8);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox8]));
			w24.Position = 1;
			this.hbox1.Add(this.vbox6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox6]));
			w25.Position = 1;
			this.vbox20.Add(this.hbox1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.hbox1]));
			w26.Position = 2;
			this.Add(this.vbox20);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 559;
			this.DefaultHeight = 300;
			this.Show();
			this.btnEditar.Clicked += new global::System.EventHandler(this.OnBtnEditarClicked);
			this.btnListar.Clicked += new global::System.EventHandler(this.OnBtnListarClicked);
			this.btnAgregar.Clicked += new global::System.EventHandler(this.OnBtnAgregarClicked);
			this.trvEmpresa.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTrvEmpresaRowActivated);
		}
	}
}
