
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Visualizar_Plantilla
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action InicioAction;

		private global::Gtk.Action MenAction;

		private global::Gtk.Action findAction;

		private global::Gtk.VBox vbox4;

		private global::Gtk.MenuBar menubar5;

		private global::Gtk.Frame frame5;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Label label25;

		private global::Gtk.Entry entry22;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Toolbar toolbar3;

		private global::Gtk.Label label26;

		private global::Gtk.HBox hbox21;

		private global::Gtk.CheckButton checkbutton3;

		private global::Gtk.CheckButton checkbutton4;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Visualizar_Plantilla
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.InicioAction = new global::Gtk.Action("InicioAction", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
			this.InicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
			w1.Add(this.InicioAction, null);
			this.MenAction = new global::Gtk.Action("MenAction", global::Mono.Unix.Catalog.GetString("Menú"), null, null);
			this.MenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menú");
			w1.Add(this.MenAction, null);
			this.findAction = new global::Gtk.Action("findAction", null, null, "gtk-find");
			this.findAction.ShortLabel = "";
			w1.Add(this.findAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Visualizar_Plantilla";
			this.Title = global::Mono.Unix.Catalog.GetString("Visualizar_Plantilla");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Visualizar_Plantilla.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar5\'><menu name=\'InicioAction\' action=\'InicioAction\'/><me" +
					"nu name=\'MenAction\' action=\'MenAction\'/></menubar></ui>");
			this.menubar5 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar5")));
			this.menubar5.Name = "menubar5";
			this.vbox4.Add(this.menubar5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.menubar5]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame5 = new global::Gtk.Frame();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox19.Add(this.label25);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.label25]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.entry22 = new global::Gtk.Entry();
			this.entry22.CanFocus = true;
			this.entry22.Name = "entry22";
			this.entry22.IsEditable = true;
			this.entry22.InvisibleChar = '•';
			this.hbox19.Add(this.entry22);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.entry22]));
			w4.Position = 1;
			// Container child hbox19.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar3\'><toolitem name=\'findAction\' action=\'findAction\'/></t" +
					"oolbar></ui>");
			this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar3")));
			this.toolbar3.Name = "toolbar3";
			this.toolbar3.ShowArrow = false;
			this.hbox20.Add(this.toolbar3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.toolbar3]));
			w5.Position = 0;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Ordenar por:");
			this.hbox20.Add(this.label26);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.label26]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.checkbutton3 = new global::Gtk.CheckButton();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString("Ascendente");
			this.checkbutton3.Active = true;
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.hbox21.Add(this.checkbutton3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.checkbutton3]));
			w7.Position = 0;
			// Container child hbox21.Gtk.Box+BoxChild
			this.checkbutton4 = new global::Gtk.CheckButton();
			this.checkbutton4.CanFocus = true;
			this.checkbutton4.Name = "checkbutton4";
			this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString("Descendente");
			this.checkbutton4.DrawIndicator = true;
			this.checkbutton4.UseUnderline = true;
			this.hbox21.Add(this.checkbutton4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.checkbutton4]));
			w8.Position = 1;
			this.hbox20.Add(this.hbox21);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.hbox21]));
			w9.Position = 2;
			this.hbox19.Add(this.hbox20);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.hbox20]));
			w10.Position = 2;
			this.GtkAlignment.Add(this.hbox19);
			this.frame5.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("NÓMINAS");
			this.GtkLabel2.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel2;
			this.vbox4.Add(this.frame5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame5]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow.Add(this.treeview2);
			this.vbox4.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w15.Position = 2;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 682;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
