
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Detalle_Empleado
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action InicioAction;

		private global::Gtk.Action MenAction;

		private global::Gtk.VBox vbox5;

		private global::Gtk.MenuBar menubar6;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.ComboBox cmbEmpresa;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button btnBuscarEm;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label2;

		private global::Gtk.HBox hbox3;

		private global::Gtk.ComboBox cmbSucursal;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Button btnBuscarS;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvEmpleado;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.HSeparator hseparator1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Detalle_Empleado
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.InicioAction = new global::Gtk.Action("InicioAction", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
			this.InicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
			w1.Add(this.InicioAction, null);
			this.MenAction = new global::Gtk.Action("MenAction", global::Mono.Unix.Catalog.GetString("Menú"), null, null);
			this.MenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menú");
			w1.Add(this.MenAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Detalle_Empleado";
			this.Title = global::Mono.Unix.Catalog.GetString("Detalle_Empleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Detalle_Empleado.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar6\'><menu name=\'InicioAction\' action=\'InicioAction\'/><me" +
					"nu name=\'MenAction\' action=\'MenAction\'/></menubar></ui>");
			this.menubar6 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar6")));
			this.menubar6.Name = "menubar6";
			this.vbox5.Add(this.menubar6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.menubar6]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Empresa:");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.cmbEmpresa = global::Gtk.ComboBox.NewText();
			this.cmbEmpresa.Name = "cmbEmpresa";
			this.hbox4.Add(this.cmbEmpresa);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.cmbEmpresa]));
			w4.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox4.Add(this.alignment2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment2]));
			w5.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox4.Add(this.alignment1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment1]));
			w6.Position = 2;
			this.hbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox4]));
			w7.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnBuscarEm = new global::Gtk.Button();
			this.btnBuscarEm.CanFocus = true;
			this.btnBuscarEm.Name = "btnBuscarEm";
			this.btnBuscarEm.UseUnderline = true;
			this.btnBuscarEm.Label = global::Mono.Unix.Catalog.GetString("Buscar por Empresa");
			this.hbox1.Add(this.btnBuscarEm);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnBuscarEm]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Sucursal:");
			this.hbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.cmbSucursal = global::Gtk.ComboBox.NewText();
			this.cmbSucursal.Name = "cmbSucursal";
			this.hbox3.Add(this.cmbSucursal);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.cmbSucursal]));
			w11.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.hbox3.Add(this.alignment4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment4]));
			w12.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.hbox3.Add(this.alignment3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment3]));
			w13.Position = 2;
			this.hbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
			w14.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnBuscarS = new global::Gtk.Button();
			this.btnBuscarS.CanFocus = true;
			this.btnBuscarS.Name = "btnBuscarS";
			this.btnBuscarS.UseUnderline = true;
			this.btnBuscarS.Label = global::Mono.Unix.Catalog.GetString("Buscar por sucursal");
			this.hbox2.Add(this.btnBuscarS);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnBuscarS]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvEmpleado = new global::Gtk.TreeView();
			this.trvEmpleado.CanFocus = true;
			this.trvEmpleado.Name = "trvEmpleado";
			this.GtkScrolledWindow.Add(this.trvEmpleado);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w18.Position = 2;
			this.GtkAlignment.Add(this.vbox1);
			this.frame1.Add(this.GtkAlignment);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("DETALLE EMPLEADO");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.vbox5.Add(this.frame1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.frame1]));
			w21.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			// Container child alignment10.Gtk.Container+ContainerChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.alignment10.Add(this.hseparator1);
			this.vbox6.Add(this.alignment10);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment10]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox5.Add(this.vbox6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 797;
			this.DefaultHeight = 294;
			this.Show();
			this.btnBuscarEm.Clicked += new global::System.EventHandler(this.OnBtnBuscarEmClicked);
			this.btnBuscarS.Clicked += new global::System.EventHandler(this.OnBtnBuscarSClicked);
		}
	}
}
