
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Editar_Sucursal
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action INICIOAction;

		private global::Gtk.Action MENAction;

		private global::Gtk.VBox vbox24;

		private global::Gtk.MenuBar menubar16;

		private global::Gtk.Frame frame16;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox52;

		private global::Gtk.Button btnEditar;

		private global::Gtk.Button button12;

		private global::Gtk.Button button15;

		private global::Gtk.Label GtkLabel5;

		private global::Gtk.HBox hbox7;

		private global::Gtk.VBox vbox17;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvSucursal;

		private global::Gtk.HBox hbox9;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label21;

		private global::Gtk.Entry txtId;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label Nombre;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.HBox hbox12;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Label Extension;

		private global::Gtk.Entry txtExtension;

		private global::Gtk.HBox hbox13;

		private global::Gtk.HBox hbox16;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Label label27;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.ComboBox cmbEmpresa;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Editar_Sucursal
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.INICIOAction = new global::Gtk.Action("INICIOAction", global::Mono.Unix.Catalog.GetString("INICIO"), null, null);
			this.INICIOAction.ShortLabel = global::Mono.Unix.Catalog.GetString("INICIO");
			w1.Add(this.INICIOAction, null);
			this.MENAction = new global::Gtk.Action("MENAction", global::Mono.Unix.Catalog.GetString("MENÚ"), null, null);
			this.MENAction.ShortLabel = global::Mono.Unix.Catalog.GetString("MENÚ");
			w1.Add(this.MENAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Editar_Sucursal";
			this.Title = global::Mono.Unix.Catalog.GetString("Editar_Sucursal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Editar_Sucursal.Gtk.Container+ContainerChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar16\'><menu name=\'INICIOAction\' action=\'INICIOAction\'/><m" +
					"enu name=\'MENAction\' action=\'MENAction\'/></menubar></ui>");
			this.menubar16 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar16")));
			this.menubar16.Name = "menubar16";
			this.vbox24.Add(this.menubar16);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.menubar16]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.frame16 = new global::Gtk.Frame();
			this.frame16.Name = "frame16";
			this.frame16.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame16.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox52 = new global::Gtk.HBox();
			this.hbox52.Name = "hbox52";
			this.hbox52.Spacing = 6;
			// Container child hbox52.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.BorderWidth = ((uint)(15));
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar ");
			this.hbox52.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.btnEditar]));
			w3.Position = 0;
			// Container child hbox52.Gtk.Box+BoxChild
			this.button12 = new global::Gtk.Button();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.BorderWidth = ((uint)(15));
			this.button12.Label = global::Mono.Unix.Catalog.GetString("Listar");
			this.hbox52.Add(this.button12);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.button12]));
			w4.Position = 1;
			// Container child hbox52.Gtk.Box+BoxChild
			this.button15 = new global::Gtk.Button();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.BorderWidth = ((uint)(12));
			this.button15.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox52.Add(this.button15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.button15]));
			w5.Position = 2;
			this.GtkAlignment.Add(this.hbox52);
			this.frame16.Add(this.GtkAlignment);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("SUCURSALES");
			this.GtkLabel5.UseMarkup = true;
			this.frame16.LabelWidget = this.GtkLabel5;
			this.vbox24.Add(this.frame16);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.frame16]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvSucursal = new global::Gtk.TreeView();
			this.trvSucursal.CanFocus = true;
			this.trvSucursal.Name = "trvSucursal";
			this.GtkScrolledWindow.Add(this.trvSucursal);
			this.vbox17.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.GtkScrolledWindow]));
			w10.Position = 0;
			// Container child vbox17.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("IdSucursal");
			this.hbox10.Add(this.label21);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label21]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.txtId = new global::Gtk.Entry();
			this.txtId.CanFocus = true;
			this.txtId.Name = "txtId";
			this.txtId.IsEditable = true;
			this.txtId.InvisibleChar = '•';
			this.hbox10.Add(this.txtId);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.txtId]));
			w12.Position = 1;
			this.hbox9.Add(this.hbox10);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox10]));
			w13.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.Nombre = new global::Gtk.Label();
			this.Nombre.Name = "Nombre";
			this.Nombre.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.hbox11.Add(this.Nombre);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.Nombre]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.hbox11.Add(this.txtNombre);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.txtNombre]));
			w15.Position = 1;
			this.hbox9.Add(this.hbox11);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox11]));
			w16.Position = 1;
			this.vbox17.Add(this.hbox9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.hbox9]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.Extension = new global::Gtk.Label();
			this.Extension.Name = "Extension";
			this.Extension.LabelProp = global::Mono.Unix.Catalog.GetString("Extension");
			this.hbox14.Add(this.Extension);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.Extension]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.txtExtension = new global::Gtk.Entry();
			this.txtExtension.CanFocus = true;
			this.txtExtension.Name = "txtExtension";
			this.txtExtension.IsEditable = true;
			this.txtExtension.InvisibleChar = '•';
			this.hbox14.Add(this.txtExtension);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.txtExtension]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox12.Add(this.hbox14);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.hbox14]));
			w20.Position = 0;
			w20.Expand = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Empresa");
			this.hbox17.Add(this.label27);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.label27]));
			w21.Position = 0;
			// Container child hbox17.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox17.Add(this.fixed1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.fixed1]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox16.Add(this.hbox17);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.hbox17]));
			w23.Position = 0;
			// Container child hbox16.Gtk.Box+BoxChild
			this.cmbEmpresa = global::Gtk.ComboBox.NewText();
			this.cmbEmpresa.Name = "cmbEmpresa";
			this.hbox16.Add(this.cmbEmpresa);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.cmbEmpresa]));
			w24.Position = 1;
			this.hbox13.Add(this.hbox16);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hbox16]));
			w25.Position = 0;
			this.hbox12.Add(this.hbox13);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.hbox13]));
			w26.Position = 1;
			this.vbox17.Add(this.hbox12);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.hbox12]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox7.Add(this.vbox17);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox17]));
			w28.Position = 0;
			this.vbox24.Add(this.hbox7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox7]));
			w29.Position = 2;
			this.Add(this.vbox24);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 463;
			this.DefaultHeight = 300;
			this.Show();
			this.btnEditar.Clicked += new global::System.EventHandler(this.OnBtnEditarClicked);
			this.trvSucursal.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTrvSucursalRowActivated);
		}
	}
}
