
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Visualizar_Usuario
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action ArchivoAction;

		private global::Gtk.Action AyudaAction;

		private global::Gtk.Action findAction;

		private global::Gtk.VBox vbox4;

		private global::Gtk.MenuBar menubar3;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label12;

		private global::Gtk.Entry entry13;

		private global::Gtk.Toolbar toolbar4;

		private global::Gtk.Button button5;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvUsuarios;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Visualizar_Usuario
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.ArchivoAction = new global::Gtk.Action("ArchivoAction", global::Mono.Unix.Catalog.GetString("Archivo"), null, null);
			this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Archivo");
			w1.Add(this.ArchivoAction, null);
			this.AyudaAction = new global::Gtk.Action("AyudaAction", global::Mono.Unix.Catalog.GetString("Ayuda"), null, null);
			this.AyudaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ayuda");
			w1.Add(this.AyudaAction, null);
			this.findAction = new global::Gtk.Action("findAction", null, null, "gtk-find");
			w1.Add(this.findAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Visualizar_Usuario";
			this.Title = global::Mono.Unix.Catalog.GetString("Visualizar_Usuario");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Visualizar_Usuario.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar3\'><menu name=\'ArchivoAction\' action=\'ArchivoAction\'/><" +
					"menu name=\'AyudaAction\' action=\'AyudaAction\'/></menubar></ui>");
			this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
			this.menubar3.Name = "menubar3";
			this.vbox4.Add(this.menubar3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.menubar3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Búsqueda de usuario:");
			this.hbox5.Add(this.label12);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label12]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entry13 = new global::Gtk.Entry();
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '•';
			this.hbox5.Add(this.entry13);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entry13]));
			w4.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar4\'><toolitem name=\'findAction\' action=\'findAction\'/></t" +
					"oolbar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.hbox5.Add(this.toolbar4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.toolbar4]));
			w5.Position = 2;
			// Container child hbox5.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Listar todos");
			this.hbox5.Add(this.button5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button5]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment.Add(this.hbox5);
			this.frame3.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("USUARIOS");
			this.GtkLabel2.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel2;
			this.vbox4.Add(this.frame3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.frame3]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox4.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator1]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvUsuarios = new global::Gtk.TreeView();
			this.trvUsuarios.CanFocus = true;
			this.trvUsuarios.Name = "trvUsuarios";
			this.GtkScrolledWindow.Add(this.trvUsuarios);
			this.vbox4.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w12.Position = 3;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 557;
			this.DefaultHeight = 327;
			this.Show();
		}
	}
}
