
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Detalle_Empleado
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action InicioAction;

		private global::Gtk.Action MenAction;

		private global::Gtk.VBox vbox5;

		private global::Gtk.MenuBar menubar6;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Table table5;

		private global::Gtk.Entry entry24;

		private global::Gtk.Entry entry25;

		private global::Gtk.Entry entry26;

		private global::Gtk.Entry entry27;

		private global::Gtk.Label label27;

		private global::Gtk.Label label28;

		private global::Gtk.Label label29;

		private global::Gtk.Label label30;

		private global::Gtk.Label label31;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvPagos;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.HBox hbox24;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView trvExtras;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TreeView trvDeducciones;

		private global::Gtk.Alignment alignment11;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Detalle_Empleado
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.InicioAction = new global::Gtk.Action("InicioAction", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
			this.InicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
			w1.Add(this.InicioAction, null);
			this.MenAction = new global::Gtk.Action("MenAction", global::Mono.Unix.Catalog.GetString("Menú"), null, null);
			this.MenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menú");
			w1.Add(this.MenAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Detalle_Empleado";
			this.Title = global::Mono.Unix.Catalog.GetString("Detalle_Empleado");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Detalle_Empleado.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar6\'><menu name=\'InicioAction\' action=\'InicioAction\'/><me" +
					"nu name=\'MenAction\' action=\'MenAction\'/></menubar></ui>");
			this.menubar6 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar6")));
			this.menubar6.Name = "menubar6";
			this.vbox5.Add(this.menubar6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.menubar6]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table5 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.entry24 = new global::Gtk.Entry();
			this.entry24.CanFocus = true;
			this.entry24.Name = "entry24";
			this.entry24.IsEditable = true;
			this.entry24.InvisibleChar = '•';
			this.table5.Add(this.entry24);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table5[this.entry24]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry25 = new global::Gtk.Entry();
			this.entry25.CanFocus = true;
			this.entry25.Name = "entry25";
			this.entry25.IsEditable = true;
			this.entry25.InvisibleChar = '•';
			this.table5.Add(this.entry25);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table5[this.entry25]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry26 = new global::Gtk.Entry();
			this.entry26.CanFocus = true;
			this.entry26.Name = "entry26";
			this.entry26.IsEditable = true;
			this.entry26.InvisibleChar = '•';
			this.table5.Add(this.entry26);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table5[this.entry26]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry27 = new global::Gtk.Entry();
			this.entry27.CanFocus = true;
			this.entry27.Name = "entry27";
			this.entry27.IsEditable = true;
			this.entry27.InvisibleChar = '•';
			this.table5.Add(this.entry27);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table5[this.entry27]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.Xalign = 1F;
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres:");
			this.table5.Add(this.label27);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table5[this.label27]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.Xalign = 1F;
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos:");
			this.table5.Add(this.label28);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table5[this.label28]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.Xalign = 1F;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Cédula:");
			this.table5.Add(this.label29);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table5[this.label29]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de Ingreso:");
			this.table5.Add(this.label30);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5[this.label30]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Salario básico:");
			this.table5.Add(this.label31);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table5[this.label31]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.table5.Add(this.txtNombre);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table5[this.txtNombre]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add(this.table5);
			this.frame6.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("NÓMINAS");
			this.GtkLabel2.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel2;
			this.vbox5.Add(this.frame6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.frame6]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			// Container child alignment10.Gtk.Container+ContainerChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.alignment10.Add(this.hseparator1);
			this.vbox6.Add(this.alignment10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment10]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvPagos = new global::Gtk.TreeView();
			this.trvPagos.CanFocus = true;
			this.trvPagos.Name = "trvPagos";
			this.GtkScrolledWindow.Add(this.trvPagos);
			this.GtkAlignment2.Add(this.GtkScrolledWindow);
			this.frame4.Add(this.GtkAlignment2);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("PAGOS DEL EMPLEADO");
			this.GtkLabel4.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel4;
			this.hbox22.Add(this.frame4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.frame4]));
			w21.Position = 0;
			this.vbox6.Add(this.hbox22);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox22]));
			w22.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.GtkAlignment1.Add(this.fixed1);
			this.frame3.Add(this.GtkAlignment1);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("EXTRAS                                       DEDUCCIONES");
			this.GtkLabel3.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel3;
			this.vbox6.Add(this.frame3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.frame3]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.trvExtras = new global::Gtk.TreeView();
			this.trvExtras.CanFocus = true;
			this.trvExtras.Name = "trvExtras";
			this.GtkScrolledWindow1.Add(this.trvExtras);
			this.hbox24.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.GtkScrolledWindow1]));
			w27.Position = 0;
			// Container child hbox24.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.trvDeducciones = new global::Gtk.TreeView();
			this.trvDeducciones.CanFocus = true;
			this.trvDeducciones.Name = "trvDeducciones";
			this.GtkScrolledWindow2.Add(this.trvDeducciones);
			this.hbox24.Add(this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.GtkScrolledWindow2]));
			w29.Position = 1;
			this.vbox6.Add(this.hbox24);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox24]));
			w30.Position = 3;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.vbox6.Add(this.alignment11);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.alignment11]));
			w31.Position = 4;
			this.vbox5.Add(this.vbox6);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
			w32.Position = 2;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 344;
			this.DefaultHeight = 471;
			this.Show();
		}
	}
}
