
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Visualizar_Pago
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action InicioAction;

		private global::Gtk.Action MenAction;

		private global::Gtk.Action InicioAction1;

		private global::Gtk.Action MenAction1;

		private global::Gtk.Action Action;

		private global::Gtk.Action findAction;

		private global::Gtk.VBox vbox10;

		private global::Gtk.MenuBar menubar8;

		private global::Gtk.Frame frame8;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Label label47;

		private global::Gtk.Entry entry36;

		private global::Gtk.HBox hbox31;

		private global::Gtk.Toolbar toolbar4;

		private global::Gtk.Label label48;

		private global::Gtk.HBox hbox33;

		private global::Gtk.CheckButton checkbutton5;

		private global::Gtk.CheckButton checkbutton6;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.VBox vbox11;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview4;

		private global::Gtk.HSeparator hseparator6;

		private global::Gtk.HBox hbox34;

		private global::Gtk.Label label49;

		private global::Gtk.Entry entry37;

		private global::Gtk.Alignment alignment14;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Visualizar_Pago
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.InicioAction = new global::Gtk.Action("InicioAction", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
			this.InicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
			w1.Add(this.InicioAction, null);
			this.MenAction = new global::Gtk.Action("MenAction", global::Mono.Unix.Catalog.GetString("Menú"), null, null);
			this.MenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menú");
			w1.Add(this.MenAction, null);
			this.InicioAction1 = new global::Gtk.Action("InicioAction1", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
			this.InicioAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
			w1.Add(this.InicioAction1, null);
			this.MenAction1 = new global::Gtk.Action("MenAction1", global::Mono.Unix.Catalog.GetString("Menú"), null, null);
			this.MenAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Menú");
			w1.Add(this.MenAction1, null);
			this.Action = new global::Gtk.Action("Action", null, null, null);
			this.Action.ShortLabel = "";
			w1.Add(this.Action, null);
			this.findAction = new global::Gtk.Action("findAction", null, null, "gtk-find");
			this.findAction.ShortLabel = "";
			w1.Add(this.findAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Visualizar_Pago";
			this.Title = global::Mono.Unix.Catalog.GetString("Visualizar_Pago");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Visualizar_Pago.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar8\'><menu name=\'InicioAction1\' action=\'InicioAction1\'/><" +
					"menu name=\'MenAction1\' action=\'MenAction1\'/></menubar></ui>");
			this.menubar8 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar8")));
			this.menubar8.Name = "menubar8";
			this.vbox10.Add(this.menubar8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.menubar8]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.label47 = new global::Gtk.Label();
			this.label47.Name = "label47";
			this.label47.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox30.Add(this.label47);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.label47]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.entry36 = new global::Gtk.Entry();
			this.entry36.CanFocus = true;
			this.entry36.Name = "entry36";
			this.entry36.IsEditable = true;
			this.entry36.InvisibleChar = '•';
			this.hbox30.Add(this.entry36);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.entry36]));
			w4.Position = 1;
			// Container child hbox30.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar4\'><toolitem/><toolitem name=\'findAction\' action=\'findA" +
					"ction\'/></toolbar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.hbox31.Add(this.toolbar4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.toolbar4]));
			w5.Position = 0;
			// Container child hbox31.Gtk.Box+BoxChild
			this.label48 = new global::Gtk.Label();
			this.label48.Name = "label48";
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString("Ordenar por:");
			this.hbox31.Add(this.label48);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.label48]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.checkbutton5 = new global::Gtk.CheckButton();
			this.checkbutton5.CanFocus = true;
			this.checkbutton5.Name = "checkbutton5";
			this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString("Ascendente");
			this.checkbutton5.Active = true;
			this.checkbutton5.DrawIndicator = true;
			this.checkbutton5.UseUnderline = true;
			this.hbox33.Add(this.checkbutton5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.checkbutton5]));
			w7.Position = 0;
			// Container child hbox33.Gtk.Box+BoxChild
			this.checkbutton6 = new global::Gtk.CheckButton();
			this.checkbutton6.CanFocus = true;
			this.checkbutton6.Name = "checkbutton6";
			this.checkbutton6.Label = global::Mono.Unix.Catalog.GetString("Descendente");
			this.checkbutton6.DrawIndicator = true;
			this.checkbutton6.UseUnderline = true;
			this.hbox33.Add(this.checkbutton6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.checkbutton6]));
			w8.Position = 1;
			this.hbox31.Add(this.hbox33);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.hbox33]));
			w9.Position = 2;
			this.hbox30.Add(this.hbox31);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.hbox31]));
			w10.Position = 2;
			this.GtkAlignment.Add(this.hbox30);
			this.frame8.Add(this.GtkAlignment);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("PAGOS");
			this.GtkLabel3.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel3;
			this.vbox10.Add(this.frame8);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.frame8]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow.Add(this.treeview4);
			this.vbox11.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.GtkScrolledWindow]));
			w15.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator();
			this.hseparator6.Name = "hseparator6";
			this.vbox11.Add(this.hseparator6);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hseparator6]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox34 = new global::Gtk.HBox();
			this.hbox34.Name = "hbox34";
			this.hbox34.Spacing = 6;
			// Container child hbox34.Gtk.Box+BoxChild
			this.label49 = new global::Gtk.Label();
			this.label49.Name = "label49";
			this.label49.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.hbox34.Add(this.label49);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.label49]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.entry37 = new global::Gtk.Entry();
			this.entry37.CanFocus = true;
			this.entry37.Name = "entry37";
			this.entry37.IsEditable = true;
			this.entry37.InvisibleChar = '•';
			this.hbox34.Add(this.entry37);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.entry37]));
			w18.Position = 1;
			// Container child hbox34.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			this.hbox34.Add(this.alignment14);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox34[this.alignment14]));
			w19.Position = 2;
			this.vbox11.Add(this.hbox34);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox34]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox10.Add(this.vbox11);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.vbox11]));
			w21.Position = 2;
			this.Add(this.vbox10);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 682;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
