
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Editar_Sucursal
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action INICIOAction;

		private global::Gtk.Action MENAction;

		private global::Gtk.VBox vbox24;

		private global::Gtk.MenuBar menubar16;

		private global::Gtk.Frame frame16;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox52;

		private global::Gtk.Button button11;

		private global::Gtk.Button button12;

		private global::Gtk.Button button15;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.Table table15;

		private global::Gtk.ComboBoxEntry comboboxentry4;

		private global::Gtk.Entry entry43;

		private global::Gtk.Entry entry44;

		private global::Gtk.Entry entry45;

		private global::Gtk.Label label57;

		private global::Gtk.Label label58;

		private global::Gtk.Label label59;

		private global::Gtk.Label label60;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Editar_Sucursal
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.INICIOAction = new global::Gtk.Action("INICIOAction", global::Mono.Unix.Catalog.GetString("INICIO"), null, null);
			this.INICIOAction.ShortLabel = global::Mono.Unix.Catalog.GetString("INICIO");
			w1.Add(this.INICIOAction, null);
			this.MENAction = new global::Gtk.Action("MENAction", global::Mono.Unix.Catalog.GetString("MENÚ"), null, null);
			this.MENAction.ShortLabel = global::Mono.Unix.Catalog.GetString("MENÚ");
			w1.Add(this.MENAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Editar_Sucursal";
			this.Title = global::Mono.Unix.Catalog.GetString("Editar_Sucursal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Editar_Sucursal.Gtk.Container+ContainerChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar16\'><menu name=\'INICIOAction\' action=\'INICIOAction\'/><m" +
					"enu name=\'MENAction\' action=\'MENAction\'/></menubar></ui>");
			this.menubar16 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar16")));
			this.menubar16.Name = "menubar16";
			this.vbox24.Add(this.menubar16);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.menubar16]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.frame16 = new global::Gtk.Frame();
			this.frame16.Name = "frame16";
			this.frame16.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame16.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox52 = new global::Gtk.HBox();
			this.hbox52.Name = "hbox52";
			this.hbox52.Spacing = 6;
			// Container child hbox52.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.BorderWidth = ((uint)(15));
			this.button11.Label = global::Mono.Unix.Catalog.GetString("Editar ");
			this.hbox52.Add(this.button11);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.button11]));
			w3.Position = 0;
			// Container child hbox52.Gtk.Box+BoxChild
			this.button12 = new global::Gtk.Button();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.BorderWidth = ((uint)(15));
			this.button12.Label = global::Mono.Unix.Catalog.GetString("Listar");
			this.hbox52.Add(this.button12);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.button12]));
			w4.Position = 1;
			// Container child hbox52.Gtk.Box+BoxChild
			this.button15 = new global::Gtk.Button();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.BorderWidth = ((uint)(12));
			this.button15.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox52.Add(this.button15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.button15]));
			w5.Position = 2;
			this.GtkAlignment.Add(this.hbox52);
			this.frame16.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("SUCURSALES");
			this.GtkLabel2.UseMarkup = true;
			this.frame16.LabelWidget = this.GtkLabel2;
			this.vbox24.Add(this.frame16);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.frame16]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.table15 = new global::Gtk.Table(((uint)(4)), ((uint)(2)), false);
			this.table15.Name = "table15";
			this.table15.RowSpacing = ((uint)(6));
			this.table15.ColumnSpacing = ((uint)(6));
			// Container child table15.Gtk.Table+TableChild
			this.comboboxentry4 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry4.Name = "comboboxentry4";
			this.table15.Add(this.comboboxentry4);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table15[this.comboboxentry4]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.entry43 = new global::Gtk.Entry();
			this.entry43.CanFocus = true;
			this.entry43.Name = "entry43";
			this.entry43.IsEditable = true;
			this.entry43.InvisibleChar = '•';
			this.table15.Add(this.entry43);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table15[this.entry43]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.entry44 = new global::Gtk.Entry();
			this.entry44.CanFocus = true;
			this.entry44.Name = "entry44";
			this.entry44.IsEditable = true;
			this.entry44.InvisibleChar = '•';
			this.table15.Add(this.entry44);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table15[this.entry44]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.entry45 = new global::Gtk.Entry();
			this.entry45.CanFocus = true;
			this.entry45.Name = "entry45";
			this.entry45.IsEditable = true;
			this.entry45.InvisibleChar = '•';
			this.table15.Add(this.entry45);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table15[this.entry45]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.label57 = new global::Gtk.Label();
			this.label57.Name = "label57";
			this.label57.Xalign = 1F;
			this.label57.LabelProp = global::Mono.Unix.Catalog.GetString("ID:");
			this.table15.Add(this.label57);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table15[this.label57]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.label58 = new global::Gtk.Label();
			this.label58.Name = "label58";
			this.label58.Xalign = 1F;
			this.label58.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre:");
			this.table15.Add(this.label58);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table15[this.label58]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.label59 = new global::Gtk.Label();
			this.label59.Name = "label59";
			this.label59.Xalign = 1F;
			this.label59.LabelProp = global::Mono.Unix.Catalog.GetString("Extensión:");
			this.table15.Add(this.label59);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table15[this.label59]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table15.Gtk.Table+TableChild
			this.label60 = new global::Gtk.Label();
			this.label60.Name = "label60";
			this.label60.Xalign = 1F;
			this.label60.LabelProp = global::Mono.Unix.Catalog.GetString("Empresa:");
			this.table15.Add(this.label60);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table15[this.label60]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox24.Add(this.table15);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.table15]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.Add(this.vbox24);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 450;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
