
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Visualizar_Pago
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action Action;

		private global::Gtk.Action findAction;

		private global::Gtk.Action findAction1;

		private global::Gtk.Action findAction2;

		private global::Gtk.VBox vbox10;

		private global::Gtk.MenuBar menubar8;

		private global::Gtk.Frame frame8;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox30;

		private global::Gtk.Label label47;

		private global::Gtk.Entry entry36;

		private global::Gtk.HBox hbox31;

		private global::Gtk.Button btnBuscarNombre;

		private global::Gtk.Label label48;

		private global::Gtk.HBox hbox33;

		private global::Gtk.CheckButton checkbutton5;

		private global::Gtk.CheckButton checkbutton6;

		private global::Gtk.Label GtkLabel5;

		private global::Gtk.VBox vbox11;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView trvEmpleado;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView trvPagos;

		private global::Gtk.Label GtkLabel7;

		private global::Gtk.HSeparator hseparator6;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label1;

		private global::Gtk.Entry txtIDEmpleado;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label4;

		private global::Gtk.Entry txtNombre;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtST;

		private global::Gtk.Label GtkLabel6;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TreeView trvExtras;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow3;

		private global::Gtk.TreeView trvDeducciones;

		private global::Gtk.Label GtkLabel4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Visualizar_Pago
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.Action = new global::Gtk.Action("Action", null, null, null);
			w1.Add(this.Action, null);
			this.findAction = new global::Gtk.Action("findAction", null, null, "gtk-find");
			w1.Add(this.findAction, null);
			this.findAction1 = new global::Gtk.Action("findAction1", null, null, "gtk-find");
			w1.Add(this.findAction1, null);
			this.findAction2 = new global::Gtk.Action("findAction2", null, null, "gtk-find");
			w1.Add(this.findAction2, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Visualizar_Pago";
			this.Title = global::Mono.Unix.Catalog.GetString("Visualizar_Pago");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Visualizar_Pago.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar8\'><menu/><menu/></menubar></ui>");
			this.menubar8 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar8")));
			this.menubar8.Name = "menubar8";
			this.vbox10.Add(this.menubar8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.menubar8]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox30 = new global::Gtk.HBox();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.label47 = new global::Gtk.Label();
			this.label47.Name = "label47";
			this.label47.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox30.Add(this.label47);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.label47]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.entry36 = new global::Gtk.Entry();
			this.entry36.CanFocus = true;
			this.entry36.Name = "entry36";
			this.entry36.IsEditable = true;
			this.entry36.InvisibleChar = '•';
			this.hbox30.Add(this.entry36);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.entry36]));
			w4.Position = 1;
			// Container child hbox30.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.btnBuscarNombre = new global::Gtk.Button();
			this.btnBuscarNombre.CanFocus = true;
			this.btnBuscarNombre.Name = "btnBuscarNombre";
			this.btnBuscarNombre.UseUnderline = true;
			this.btnBuscarNombre.Label = global::Mono.Unix.Catalog.GetString("Buscar por nombre");
			this.hbox31.Add(this.btnBuscarNombre);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.btnBuscarNombre]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.label48 = new global::Gtk.Label();
			this.label48.Name = "label48";
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString("Ordenar por:");
			this.hbox31.Add(this.label48);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.label48]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.checkbutton5 = new global::Gtk.CheckButton();
			this.checkbutton5.CanFocus = true;
			this.checkbutton5.Name = "checkbutton5";
			this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString("Ascendente");
			this.checkbutton5.Active = true;
			this.checkbutton5.DrawIndicator = true;
			this.checkbutton5.UseUnderline = true;
			this.hbox33.Add(this.checkbutton5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.checkbutton5]));
			w7.Position = 0;
			// Container child hbox33.Gtk.Box+BoxChild
			this.checkbutton6 = new global::Gtk.CheckButton();
			this.checkbutton6.CanFocus = true;
			this.checkbutton6.Name = "checkbutton6";
			this.checkbutton6.Label = global::Mono.Unix.Catalog.GetString("Descendente");
			this.checkbutton6.DrawIndicator = true;
			this.checkbutton6.UseUnderline = true;
			this.hbox33.Add(this.checkbutton6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.checkbutton6]));
			w8.Position = 1;
			this.hbox31.Add(this.hbox33);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.hbox33]));
			w9.Position = 2;
			this.hbox30.Add(this.hbox31);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox30[this.hbox31]));
			w10.Position = 2;
			this.GtkAlignment.Add(this.hbox30);
			this.frame8.Add(this.GtkAlignment);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("PAGOS");
			this.GtkLabel5.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel5;
			this.vbox10.Add(this.frame8);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.frame8]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.trvEmpleado = new global::Gtk.TreeView();
			this.trvEmpleado.CanFocus = true;
			this.trvEmpleado.Name = "trvEmpleado";
			this.GtkScrolledWindow.Add(this.trvEmpleado);
			this.hbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w15.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.trvPagos = new global::Gtk.TreeView();
			this.trvPagos.CanFocus = true;
			this.trvPagos.Name = "trvPagos";
			this.GtkScrolledWindow1.Add(this.trvPagos);
			this.GtkAlignment4.Add(this.GtkScrolledWindow1);
			this.frame4.Add(this.GtkAlignment4);
			this.GtkLabel7 = new global::Gtk.Label();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("PAGOS");
			this.GtkLabel7.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel7;
			this.hbox1.Add(this.frame4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frame4]));
			w19.Position = 1;
			this.vbox11.Add(this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox1]));
			w20.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator();
			this.hseparator6.Name = "hseparator6";
			this.vbox11.Add(this.hseparator6);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hseparator6]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("ID Empleado");
			this.hbox4.Add(this.label1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label1]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.txtIDEmpleado = new global::Gtk.Entry();
			this.txtIDEmpleado.CanFocus = true;
			this.txtIDEmpleado.Name = "txtIDEmpleado";
			this.txtIDEmpleado.IsEditable = false;
			this.txtIDEmpleado.InvisibleChar = '•';
			this.hbox4.Add(this.txtIDEmpleado);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.txtIDEmpleado]));
			w23.Position = 1;
			w23.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.hbox5.Add(this.label4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
			w24.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = false;
			this.txtNombre.InvisibleChar = '•';
			this.hbox5.Add(this.txtNombre);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.txtNombre]));
			w25.Position = 1;
			this.hbox4.Add(this.hbox5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
			w26.Position = 2;
			this.hbox3.Add(this.hbox4);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
			w27.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Monto Total:");
			this.alignment2.Add(this.label2);
			this.hbox3.Add(this.alignment2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.alignment2]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.txtST = new global::Gtk.Entry();
			this.txtST.CanFocus = true;
			this.txtST.Name = "txtST";
			this.txtST.IsEditable = true;
			this.txtST.InvisibleChar = '•';
			this.hbox3.Add(this.txtST);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.txtST]));
			w30.Position = 2;
			this.GtkAlignment1.Add(this.hbox3);
			this.frame3.Add(this.GtkAlignment1);
			this.GtkLabel6 = new global::Gtk.Label();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("INFO DEL EMPLEADO");
			this.GtkLabel6.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel6;
			this.vbox2.Add(this.frame3);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame3]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.trvExtras = new global::Gtk.TreeView();
			this.trvExtras.CanFocus = true;
			this.trvExtras.Name = "trvExtras";
			this.GtkScrolledWindow2.Add(this.trvExtras);
			this.GtkAlignment2.Add(this.GtkScrolledWindow2);
			this.frame1.Add(this.GtkAlignment2);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("EXTRAS DEL PAGO");
			this.GtkLabel3.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel3;
			this.hbox2.Add(this.frame1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame1]));
			w37.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.trvDeducciones = new global::Gtk.TreeView();
			this.trvDeducciones.CanFocus = true;
			this.trvDeducciones.Name = "trvDeducciones";
			this.GtkScrolledWindow3.Add(this.trvDeducciones);
			this.GtkAlignment3.Add(this.GtkScrolledWindow3);
			this.frame2.Add(this.GtkAlignment3);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("DEDUCCIONES DEL PAGO");
			this.GtkLabel4.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel4;
			this.hbox2.Add(this.frame2);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame2]));
			w41.Position = 1;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w42.Position = 1;
			this.vbox11.Add(this.vbox2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.vbox2]));
			w43.Position = 2;
			this.vbox10.Add(this.vbox11);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.vbox11]));
			w44.Position = 2;
			this.Add(this.vbox10);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 830;
			this.DefaultHeight = 467;
			this.Show();
			this.trvEmpleado.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTrvEmpleadoRowActivated);
			this.trvPagos.RowActivated += new global::Gtk.RowActivatedHandler(this.OnTrvPagosRowActivated);
		}
	}
}
