
// This file has been generated by the GUI designer. Do not modify.
namespace Nomina
{
	public partial class Agregar_Pago
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action InicioAction;

		private global::Gtk.Action MenAction;

		private global::Gtk.VBox vbox7;

		private global::Gtk.MenuBar menubar7;

		private global::Gtk.Frame frame7;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Table table6;

		private global::Gtk.Entry entry31;

		private global::Gtk.Entry entry32;

		private global::Gtk.Label label37;

		private global::Gtk.Label label38;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.VBox vbox8;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview3;

		private global::Gtk.Table table7;

		private global::Gtk.Entry entry33;

		private global::Gtk.Entry entry34;

		private global::Gtk.HBox hbox25;

		private global::Gtk.Label label43;

		private global::Gtk.ComboBoxEntry comboboxentry1;

		private global::Gtk.HBox hbox26;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Button button8;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Label label39;

		private global::Gtk.Label label41;

		private global::Gtk.Label label42;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HSeparator hseparator5;

		private global::Gtk.HBox hbox28;

		private global::Gtk.Label label45;

		private global::Gtk.Entry entry35;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Nomina.Agregar_Pago
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.InicioAction = new global::Gtk.Action("InicioAction", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
			this.InicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
			w1.Add(this.InicioAction, null);
			this.MenAction = new global::Gtk.Action("MenAction", global::Mono.Unix.Catalog.GetString("Menú"), null, null);
			this.MenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menú");
			w1.Add(this.MenAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "Nomina.Agregar_Pago";
			this.Title = global::Mono.Unix.Catalog.GetString("Agregar_Pago");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nomina.Agregar_Pago.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'menubar7\'><menu name=\'InicioAction\' action=\'InicioAction\'/><me" +
					"nu name=\'MenAction\' action=\'MenAction\'/></menubar></ui>");
			this.menubar7 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar7")));
			this.menubar7.Name = "menubar7";
			this.vbox7.Add(this.menubar7);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.menubar7]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table6 = new global::Gtk.Table(((uint)(1)), ((uint)(4)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.entry31 = new global::Gtk.Entry();
			this.entry31.CanFocus = true;
			this.entry31.Name = "entry31";
			this.entry31.IsEditable = true;
			this.entry31.InvisibleChar = '•';
			this.table6.Add(this.entry31);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table6[this.entry31]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.entry32 = new global::Gtk.Entry();
			this.entry32.CanFocus = true;
			this.entry32.Name = "entry32";
			this.entry32.IsEditable = true;
			this.entry32.InvisibleChar = '•';
			this.table6.Add(this.entry32);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table6[this.entry32]));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label37 = new global::Gtk.Label();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("ID Empleado:");
			this.table6.Add(this.label37);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table6[this.label37]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label38 = new global::Gtk.Label();
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Empleado:");
			this.table6.Add(this.label38);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table6[this.label38]));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add(this.table6);
			this.frame7.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("PAGOS");
			this.GtkLabel2.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel2;
			this.vbox7.Add(this.frame7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.frame7]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview3 = new global::Gtk.TreeView();
			this.treeview3.CanFocus = true;
			this.treeview3.Name = "treeview3";
			this.GtkScrolledWindow.Add(this.treeview3);
			this.vbox8.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.GtkScrolledWindow]));
			w11.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.table7 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table7.Name = "table7";
			this.table7.RowSpacing = ((uint)(6));
			this.table7.ColumnSpacing = ((uint)(6));
			// Container child table7.Gtk.Table+TableChild
			this.entry33 = new global::Gtk.Entry();
			this.entry33.CanFocus = true;
			this.entry33.Name = "entry33";
			this.entry33.IsEditable = true;
			this.entry33.InvisibleChar = '•';
			this.table7.Add(this.entry33);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table7[this.entry33]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.entry34 = new global::Gtk.Entry();
			this.entry34.CanFocus = true;
			this.entry34.Name = "entry34";
			this.entry34.IsEditable = true;
			this.entry34.InvisibleChar = '•';
			this.table7.Add(this.entry34);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table7[this.entry34]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.hbox25 = new global::Gtk.HBox();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.label43 = new global::Gtk.Label();
			this.label43.Name = "label43";
			this.label43.LabelProp = global::Mono.Unix.Catalog.GetString("Moneda:");
			this.hbox25.Add(this.label43);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.label43]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry1.Name = "comboboxentry1";
			this.hbox25.Add(this.comboboxentry1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox25[this.comboboxentry1]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.table7.Add(this.hbox25);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table7[this.hbox25]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.hbox26 = new global::Gtk.HBox();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.hbox26.Add(this.alignment12);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.alignment12]));
			w17.Position = 0;
			// Container child hbox26.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.hbox26.Add(this.alignment13);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.alignment13]));
			w18.Position = 1;
			// Container child hbox26.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString("Agregar Pago");
			this.hbox26.Add(this.button8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox26[this.button8]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.table7.Add(this.hbox26);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table7[this.hbox26]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.table7.Add(this.hseparator2);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table7[this.hseparator2]));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.table7.Add(this.hseparator3);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table7[this.hseparator3]));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label39 = new global::Gtk.Label();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("Nuevo Pago");
			this.table7.Add(this.label39);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table7[this.label39]));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label41 = new global::Gtk.Label();
			this.label41.Name = "label41";
			this.label41.LabelProp = global::Mono.Unix.Catalog.GetString("ID Empleado:");
			this.table7.Add(this.label41);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table7[this.label41]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table7.Gtk.Table+TableChild
			this.label42 = new global::Gtk.Label();
			this.label42.Name = "label42";
			this.label42.Xalign = 1F;
			this.label42.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha:");
			this.table7.Add(this.label42);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table7[this.label42]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox8.Add(this.table7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.table7]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator();
			this.hseparator5.Name = "hseparator5";
			this.vbox9.Add(this.hseparator5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hseparator5]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.label45 = new global::Gtk.Label();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString("ID Pago:");
			this.hbox28.Add(this.label45);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.label45]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.entry35 = new global::Gtk.Entry();
			this.entry35.CanFocus = true;
			this.entry35.Name = "entry35";
			this.entry35.IsEditable = true;
			this.entry35.InvisibleChar = '•';
			this.hbox28.Add(this.entry35);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox28[this.entry35]));
			w29.Position = 1;
			w29.Expand = false;
			this.vbox9.Add(this.hbox28);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox28]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox8.Add(this.vbox9);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
			w31.Position = 2;
			this.vbox7.Add(this.vbox8);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox8]));
			w32.Position = 2;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 574;
			this.DefaultHeight = 319;
			this.Show();
		}
	}
}
